Repository theohbrothers/docker-pagefind, pull requests merged in 2023-11, with the labels that each got.

#2 Docs (readme): Fix usage command
  README.md
  generate/templates/README.md.ps1
Labels: docs

#3 Refactor: Download binaries directly instead of using npx
  generate/definitions/VARIANTS.ps1
  generate/templates/Dockerfile.ps1
  test.ps1
  variants/1.0.3/Dockerfile
Labels: refactor

#1 Feature: Add multi arch images
  .github/workflows/ci-master-pr.yml
  generate/definitions/VARIANTS.ps1
  variants/1.0.3/Dockerfile
Labels: feature

#5 Fix: Fix `Generate-DownloadBinary` function using wrong version
  generate/templates/Dockerfile.ps1
Labels: fix

#6 Chore: Cleanup Dockerfile template
  generate/templates/Dockerfile.ps1
Labels: chore

#7 Enhancement: Bump pagefind 1.0 variants to 1.0.4
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/1.0.4/Dockerfile
  variants/1.0.4/docker-entrypoint.sh
Labels: enhancement
